name: Androide EPG - Auto Update

on:
  schedule:
    - cron: '0 */3 * * *'  # Ogni 3 ore
  workflow_dispatch:

jobs:
  update-androide-epg:
    runs-on: ubuntu-latest
    
    steps:
      - name:  Checkout branch test
        uses: actions/checkout@v3
        with:
          ref: test
          fetch-depth: 1
      
      - name:  Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name:  Install dependencies
        run: pip install requests lxml
      
      - name:  Download EPG
        run: python scripts/fetch_openepg.py
      
      - name:  Generate JSON
        run: python scripts/generate_androide_epg.py
      
      - name:  Commit and Push
        run: |
          git config user.name "Androide Update Bot"
          git config user.email "bot@androide.epg"
          git add cache/ json/
          
          # Usa fuso orario italiano
          export TZ='Europe/Rome'
          
          # Commit solo se ci sono cambiamenti
          if git diff --staged --quiet; then
            echo "Nessun cambiamento da committare"
          else
            git commit -m " EPG Update $(date +'%Y-%m-%d %H:%M') [TEST]"
            git push origin HEAD:test
          fi
